### PR TITLE
Final Milestone: Building a Clone of NY Times Article Page

### PR DESCRIPTION
**Pull request by AhmedTohamy01**
**Building a Clone of NY Times Article Page.** 

This Includes:

- Header Section.
- Main Article Section.
- Small Side Bar (Editor Picks).
- Large Side Bar (Most Popular Articles).
- "Other Articles" Section.
- Footer Section.

### CODE REVIEW

**Comment by AhmedTohamy01** [comment]
@rOluochKe  Please read the project requirement carefully before reviewing the code . You are asking for somethings is NOT in the project Requirements ! 

for the sidebar, could you please send us the screen size which you view this project on it ?
we attached a live demo link and a screen shot and everything is working perfect in the demo link.

**Comment by rOluochKe** [comment]
> @rOluochKe Please read the project requirement carefully before reviewing the code . You are asking for somethings is NOT in the project Requirements !
> 
> for the sidebar, could you please send us the screen size which you view this project on it ?
> we attached a live demo link and a screen shot and everything is working perfect in the demo link.

### The screenshot of the sidebar is attached above from the previous review and attached below is the project requirement for the navigation bar
navigation requiremnets
### refer from the original design for the page structure

**Comment by AhmedTohamy01** [comment]
@rOluochKe I don't know from where you bring this list!

We are getting our task list from the technical curriculum , Not from anywhere else! and all your requested requirements doesn't exist in the requirement list in the Technical curriculum.!  

and you wrote to us:
**_On the top right-most of the navigation bar, should have 2 buttons_**

The buttons are there in the code with a button tag!   2 buttons ! PLEASE read the code carefully before sending your review. and also read the project requirements carefully. 

**Here is the project requirements from Odin Project:**

https://www.theodinproject.com/courses/html5-and-css3/lessons/positioning-and-floating-elements

**and here is Microverse "Project Specific Requirements':**

**Project specific**
Please use <aside> tag for Editor's picks section on the rightmost side.
Elements aligned with a combination of all three techniques (float, flex and grid)

**Comment by AhmedTohamy01** [comment]
@rOluochKe  and please tell us where in your requirement list which you sent we can find anything talking about "sticky navigation bar" ?

And you didn't send us the screen size which you are using to display the project , the screen shot is not enough, we need specific information to be able to work with it, this is NOT a review to help.!

**Comment by AhmedTohamy01** [comment]
@rOluochKe  We can NOT implement requests that doesn't exist in the project requirements & you don't want to help us by telling us what screen size you are using to display the project!

We will escalate the issue to Student Success Team!

**Comment by AhmedTohamy01** [comment]
@MarioDena  Hi man, Thank you for the Professional Helpful Review, 

Although it has more comments , but This is really make sense and very helpful review , this is a prove that we don't mind if TSEs commented on our code, but we need something make sense and they should explain what they want in a clear way (like you). 
**Not just saying "This is wrong, fix it!"**

**Comment by SofiBretz** [comment]
Well done Team 👏

Project Approved! ✨
You did all the changes required previously. 
Good Luck with your next project. Happy coding!

You can merge 👍
SofiBretz.

**Comment by AhmedTohamy01** [comment]
@SofiBretz  Thank you so much Sofi for your professional and rapid review

**Pull request merged**
